version: 2.1

jobs:
  build:
    working_directory: /tmp
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y jupyter-nbconvert
            jupyter-nbconvert --execute ./ml.ipynb
      - store_artifacts:
          path: ./ml.html
          destination: ml.html

