version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run:
        command: |
          sudo apt install -y jupyter-nbconvert
          jupyter-nbconvert --execute ./ml.ipynb
      - store_artifacts:
        path: ./ml.html
        destination: ml.html
