version: 2.1

jobs:
  build:
    working_directory: ~/ccibuild
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install nbconvert
      - run: jupyter nbconvert --to html --execute ./ml.ipynb
      - store_artifacts:
          path: ./ml.html
          destination: ml.html

