version: 2.1

jobs:
  build:
    working_directory: ~/ccibuild
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo apt install -y jupyter-nbconvert
      - run: jupyter-nbconvert --execute ./ml.ipynb
      - store_artifacts:
          path: ./ml.html
          destination: ml.html

